telegram_bot_token: YOUR_BOT_TOKEN_HERE
http_api_url: http://127.0.0.1:8123
http_api_secret: YOUR_API_SECRET_HERE
allowed_usernames:
  - username1
  - username2
logging:
  level: INFO
  file: /var/log/amnezia-vds-bot.log
